"""Golden parity corpus pinning the TS expression-grammar port to the engine.

Regenerate (from webapp/backend): `python tests/test_expr_golden.py`
The committed JSON is asserted byte-identical below, so ANY engine grammar change
fails CI here until the corpus is regenerated AND the TS port
(webapp/frontend/src/builder/expr/) is re-synced against parity.test.ts.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from lab_devices.experiment.errors import ExpressionError
from lab_devices.experiment.expr import parse_expression, tokenize

GOLDEN_PATH = (
    Path(__file__).resolve().parents[3]
    / "webapp/frontend/src/builder/expr/__goldens__/expr-parity.json"
)

CORPUS: list[str] = [
    # literals and bindings
    "1",
    "0.5",
    "42",
    "true",
    "false",
    "od",
    "feed_ml",
    "_x1",
    "'chemostat'",
    "''",
    "'a b c'",
    "5min",
    "30s",
    "250ms",
    "1.5h",
    "0.5s",
    "9" * 400,  # huge int: fine in both (JS precision loss is irrelevant client-side)
    "9" * 400 + ".0",  # huge float: non-finite in both
    # stat calls and windows
    "mean(od)",
    "last(od)",
    "min(od)",
    "max(od)",
    "count(od)",
    "mean(od, last=5)",
    "mean(od, last=30s)",
    "mean (od , last=5)",
    "count(od,last=90s) > 0 and mean(od,last=90s) > 2.0",
    # operators, precedence, unary
    "not a and b + 2 * c < 5 or true",
    "-x + 2",
    "not not true",
    "-(-1)",
    "a / b * c - d",
    "(a or b) and c",
    "mode == 'chemostat'",
    "x != 'a'",
    "last(od) > 0.5",
    "5min + 30s",
    "cycle_min * 1min",
    # errors: lexing
    "od > §3",
    "x == 'oops",
    "a & b",
    "#tag",
    "!x",
    # errors: parsing
    "",
    "   ",
    "1 +",
    "mean(",
    "mean(od",
    "mean(od,",
    "mean(od, last=",
    "median(od)",
    "mean(and)",
    "mean(5)",
    "mean(od, first=3)",
    "mean(od, last=0)",
    "mean(od, last=2.5)",
    "mean(od, last=-1)",
    "1 < x < 2",
    "x and",
    "()",
    "not",
    "true false",
    "1 1",
    ") od",
    "and od",
    "5min(od)",
    "x == == 2",
    "(" * 65 + "1" + ")" * 65,  # depth cap
    "-" * 65 + "1",
    "5min_x",  # \b guard: NUMBER + NAME, then trailing-input error
]

_POS_RE = re.compile(r"at position (\d+)")
# NB: positions are extracted from engine messages; the corpus must never include a
# FAILING expression whose own text contains "at position N" (the message embeds the text).


def _case(expr: str) -> dict[str, object]:
    case: dict[str, object] = {"expr": expr}
    try:
        toks = tokenize(expr)
        case["tokens"] = [
            {"kind": t.kind, "text": t.text, "pos": t.pos} for t in toks if t.kind != "END"
        ]
        case["lex_error_pos"] = None
    except ExpressionError as e:
        m = _POS_RE.search(str(e))
        case["tokens"] = None
        case["lex_error_pos"] = int(m.group(1)) if m else None
    try:
        parse_expression(expr)
        case["parse_ok"] = True
        case["parse_error_pos"] = None
        case["parse_error"] = None
    except ExpressionError as e:
        m = _POS_RE.search(str(e))
        case["parse_ok"] = False
        case["parse_error_pos"] = int(m.group(1)) if m else None
        case["parse_error"] = str(e)
    return case


def build_golden() -> dict[str, object]:
    return {
        "note": "generated by webapp/backend/tests/test_expr_golden.py -- do not edit by hand",
        "cases": [_case(e) for e in CORPUS],
    }


def _dump(data: dict[str, object]) -> str:
    return json.dumps(data, indent=1, sort_keys=True, ensure_ascii=False) + "\n"


def test_committed_golden_matches_engine() -> None:
    assert GOLDEN_PATH.read_text() == _dump(build_golden()), (
        "expr parity golden drifted from the engine grammar; regenerate with "
        "`python tests/test_expr_golden.py` (from webapp/backend) and re-sync the TS port"
    )


if __name__ == "__main__":
    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN_PATH.write_text(_dump(build_golden()))
    print(f"wrote {GOLDEN_PATH}")
