/** TS port of the engine expression tokenizer (src/lab_devices/experiment/expr.py
 * `_TOKEN_RE`/`tokenize` + durations.py DURATION_PATTERN). Drift-pinned by the golden
 * parity corpus (__goldens__/expr-parity.json, regenerated by
 * webapp/backend/tests/test_expr_golden.py) — change only in lockstep with the engine. */

export type TokenKind = 'DURATION' | 'NUMBER' | 'STRING' | 'NAME' | 'OP' | 'END'

export interface Token {
  kind: TokenKind
  text: string
  pos: number
}

export interface LexError {
  pos: number
  char: string
}

export interface LexResult {
  /** Always END-terminated, even after an error (everything before the bad char). */
  tokens: Token[]
  error: LexError | null
}

export const STAT_FNS = ['last', 'mean', 'min', 'max', 'count'] as const
export const KEYWORDS = ['and', 'or', 'not', 'true', 'false'] as const

const TOKEN_KINDS = ['DURATION', 'NUMBER', 'STRING', 'NAME', 'OP'] as const

// DURATION before NUMBER so `30s` is one token; unit alternation longest-first
// (`min|ms|s|h`) and \b so `5min_x` lexes as NUMBER + NAME — all as in the engine.
const TOKEN_RE =
  /\s+|(?<DURATION>\d+(?:\.\d+)?(?:min|ms|s|h)\b)|(?<NUMBER>\d+(?:\.\d+)?)|(?<STRING>'[^']*')|(?<NAME>[A-Za-z_][A-Za-z0-9_]*)|(?<OP><=|>=|==|!=|[-+*/(),<>=])/y

export function tokenize(text: string): LexResult {
  const tokens: Token[] = []
  let pos = 0
  while (pos < text.length) {
    TOKEN_RE.lastIndex = pos
    const m = TOKEN_RE.exec(text)
    if (m === null) {
      // The engine raises here; the editor keeps what it has so highlighting can
      // still paint everything before the bad character.
      tokens.push({ kind: 'END', text: '', pos })
      return { tokens, error: { pos, char: text[pos] } }
    }
    const groups = m.groups ?? {}
    for (const kind of TOKEN_KINDS) {
      const t = groups[kind]
      if (t !== undefined) {
        tokens.push({ kind, text: t, pos })
        break
      }
    }
    pos = TOKEN_RE.lastIndex
  }
  tokens.push({ kind: 'END', text: '', pos: text.length })
  return { tokens, error: null }
}
